AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: AWS Sam Backend for Tower

Parameters:
  Region:
    Description: The AWS SDK Chime REGION
    Default: "eu-central-1"
    Type: String
  AuthUrl:
    Description: The url to check the basic auth tokens against
    Type: String
  AllowOrigin:
    Description: Value for the Access-Control-Allow-Origin CORS-Header
    Default: ""
    Type: String
  StageName:
    Description: The name for the stage to create
    Default: "Prod"
    Type: String

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 30
    MemorySize: 128
    Environment:
      Variables:
        MEETINGS_TABLE_NAME: !Ref Meetings
        REGION: !Ref Region
        AUTH_URL: !Ref AuthUrl
  Api:
    # Workaround for https://github.com/aws/serverless-application-model/issues/191
    OpenApiVersion: 3.0.1

Resources:
  TowerApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName
      Auth:
        DefaultAuthorizer: BasicAuthLambdaTokenAuthorizer
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          BasicAuthLambdaTokenAuthorizer:
            FunctionArn: !GetAtt BasicAuthLambda.Arn
      Cors:
        AllowMethods: "'POST, GET'"
        AllowOrigin: !Sub
          - "'${Origin}'"
          - Origin: !Ref AllowOrigin
        MaxAge: "'600'"
        AllowCredentials: true
      GatewayResponses:
        UNAUTHORIZED:
          StatusCode: 401
          ResponseParameters:
            Headers:
              WWW-Authenticate: "'Basic'"
          ResponseTemplates:
            "application/json": {"message": "Unauthorized"}
  ChimeMeetingsAccessPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: ChimeMeetingsAccess
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 'chime:CreateMeeting'
              - 'chime:TagMeeting'
              - 'chime:TagResource'
              - 'chime:DeleteMeeting'
              - 'chime:GetMeeting'
              - 'chime:ListMeetings'
              - 'chime:BatchCreateAttendee'
              - 'chime:CreateAttendee'
              - 'chime:DeleteAttendee'
              - 'chime:GetAttendee'
              - 'chime:ListAttendees'
              - 's3:GetBucketPolicy'
              - 's3:GetBucketLocation'
            Resource: '*'
      Roles:
        - Ref: ChimeSdkStartLambdaRole
        - Ref: ChimeSdkJoinLambdaRole
        - Ref: ChimeSdkEndLambdaRole
        - Ref: ChimeSdkDeleteAttendeeLambdaRole
        - Ref: ChimeSdkPollLambdaRole
  Meetings:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "Title"
          AttributeType: "S"
        - AttributeName: "DateTime"
          AttributeType: "S"
        - AttributeName: "PartitionKey"
          AttributeType: "S"
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: "Title"
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: "DateTime"
          KeySchema:
            - AttributeName: "PartitionKey"
              KeyType: HASH
            - AttributeName: "DateTime"
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: "TTL"
        Enabled: true
  CallRecords:
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "Caller"
          AttributeType: "S"
        - AttributeName: "Assistant"
          AttributeType: "S"
        - AttributeName: "StartDateTime"
          AttributeType: "S"
        - AttributeName: "AcceptDateTime"
          AttributeType: "S"
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: "Caller"
          KeyType: HASH
        - AttributeName: "StartDateTime"
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: "Assistant"
          KeySchema:
            - AttributeName: "Assistant"
              KeyType: HASH
            - AttributeName: "AcceptDateTime"
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
  ChimeSdkIndexLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers.index
      CodeUri: build/
      Events:
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref TowerApi
            Path: /
            Method: GET
  ChimeSdkStartLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers.start
      CodeUri: build/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Meetings
        - DynamoDBCrudPolicy:
            TableName: !Ref CallRecords
      Events:
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref TowerApi
            Path: /start
            Method: POST
  ChimeSdkJoinLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers.join
      CodeUri: build/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Meetings
        - DynamoDBCrudPolicy:
            TableName: !Ref CallRecords
      Events:
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref TowerApi
            Path: /join
            Method: POST
  ChimeSdkDeleteAttendeeLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers.deleteAttendee
      CodeUri: build/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Meetings
        - DynamoDBCrudPolicy:
            TableName: !Ref CallRecords
      Events:
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref TowerApi
            Path: /deleteAttendee
            Method: POST
  ChimeSdkEndLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers.end
      CodeUri: build/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Meetings
        - DynamoDBCrudPolicy:
            TableName: !Ref CallRecords
      Events:
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref TowerApi
            Path: /end
            Method: POST
  ChimeSdkPollLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers.poll
      CodeUri: build/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Meetings
      Events:
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref TowerApi
            Path: /poll
            Method: GET
  BasicAuthLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/
      Handler: handlers.auth
Outputs:
  ApiURL:
    Description: "API endpoint URL for Prod environment"
    Value: !Sub "https://${TowerApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/"
