AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: AWS Sam Backend for Tower

Parameters:
  AuthUrl:
    Description: The url to check the basic auth tokens against
    Type: String
  AllowOrigin:
    Description: Value for the Access-Control-Allow-Origin CORS-Header
    Default: ""
    Type: String
  StageName:
    Description: The name for the stage to create
    Default: "Prod"
    Type: String
  CommunicationServicesEndpoint:
    Description: The Azure Communication Services Endpoint to use
    Default: ""
    Type: String
  CommunicationServicesAccesskey:
    Description: The access key to use to connect to Azure Communication Services
    Default: ""
    Type: String
  Hours:
    Description: The regular opening hours of the service
    Default: ""
    Type: String
  ExtraHours:
    Description: Opening hours that apply in addition to the regular opening hours
    Default: ""
    Type: String
  Holidays:
    Description: Days where the normal opening hours don't apply
    Default: ""
    Type: String
  Tz:
    Description: The time zone to use for the opening hours
    Default: ""
    Type: String

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 30
    MemorySize: 128
    Environment:
      Variables:
        ASSISTANCE_REQUESTS_TABLE_NAME: !Ref AssistanceRequests
        CALL_RECORDS_TABLE_NAME: !Ref CallRecords
        COMMUNICATION_USER_IDS_TABLE_NAME: !Ref CommunicationUserIds
        AUTH_URL: !Ref AuthUrl
        COMMUNICATION_SERVICES_ENDPOINT: !Ref CommunicationServicesEndpoint
        COMMUNICATION_SERVICES_ACCESSKEY: !Ref CommunicationServicesAccesskey
        HOURS: !Ref Hours
        EXTRA_HOURS: !Ref ExtraHours
        HOLIDAYS: !Ref Holidays
        TZ: !Ref Tz
  Api:
    # Workaround for https://github.com/aws/serverless-application-model/issues/191
    OpenApiVersion: 3.0.1

Resources:
  TowerApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName
      Auth:
        DefaultAuthorizer: BasicAuthLambdaTokenAuthorizer
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          BasicAuthLambdaTokenAuthorizer:
            FunctionArn: !GetAtt BasicAuthLambda.Arn
      Cors:
        AllowMethods: "'POST, GET'"
        AllowOrigin: !Sub
          - "'${Origin}'"
          - Origin: !Ref AllowOrigin
        MaxAge: "'600'"
        AllowCredentials: true
      GatewayResponses:
        UNAUTHORIZED:
          StatusCode: 401
          ResponseParameters:
            Headers:
              WWW-Authenticate: "'Basic'"
          ResponseTemplates:
            "application/json": {"message": "Unauthorized"}
  AssistanceRequests:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "Username"
          AttributeType: "S"
        - AttributeName: "DateTime"
          AttributeType: "S"
        - AttributeName: "PartitionKey"
          AttributeType: "S"
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: "Username"
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: "DateTime"
          KeySchema:
            - AttributeName: "PartitionKey"
              KeyType: HASH
            - AttributeName: "DateTime"
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: "TTL"
        Enabled: true
  CallRecords:
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "Meeting"
          AttributeType: "S"
        - AttributeName: "Caller"
          AttributeType: "S"
        - AttributeName: "Assistant"
          AttributeType: "S"
        - AttributeName: "StartDateTime"
          AttributeType: "S"
        - AttributeName: "AcceptDateTime"
          AttributeType: "S"
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: "Meeting"
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: "Assistant"
          KeySchema:
            - AttributeName: "Assistant"
              KeyType: HASH
            - AttributeName: "AcceptDateTime"
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: "Caller"
          KeySchema:
            - AttributeName: "Caller"
              KeyType: HASH
            - AttributeName: "StartDateTime"
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
  CommunicationUserIds:
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "Username"
          AttributeType: "S"
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: "Username"
          KeyType: HASH
  TowerBackendIndexLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers.index
      CodeUri: build/
      Events:
        Api1:
          Type: Api
          Properties:
            Auth:
              Authorizer: NONE
            RestApiId: !Ref TowerApi
            Path: /
            Method: GET
  TowerBackendRequestAssistanceLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers.requestAssistance
      CodeUri: build/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AssistanceRequests
        - DynamoDBCrudPolicy:
            TableName: !Ref CommunicationUserIds
      Events:
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref TowerApi
            Path: /requestAssistance
            Method: POST
  TowerBackendAwaitAssistanceLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers.awaitAssistance
      CodeUri: build/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AssistanceRequests
        - DynamoDBCrudPolicy:
            TableName: !Ref CommunicationUserIds
      Events:
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref TowerApi
            Path: /awaitAssistance
            Method: POST
  TowerBackendCancelAssistanceLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers.cancelAssistance
      CodeUri: build/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AssistanceRequests
        - DynamoDBCrudPolicy:
            TableName: !Ref CallRecords
      Events:
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref TowerApi
            Path: /cancelAssistance
            Method: POST
  TowerBackendAssistanceTokenLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers.assistanceToken
      CodeUri: build/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CommunicationUserIds
      Events:
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref TowerApi
            Path: /assistanceToken
            Method: GET
  TowerBackendOfferAssistanceLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers.offerAssistance
      CodeUri: build/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AssistanceRequests
      Events:
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref TowerApi
            Path: /offerAssistance
            Method: GET
  TowerBackendBeginAssistanceLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers.beginAssistance
      CodeUri: build/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AssistanceRequests
        - DynamoDBCrudPolicy:
            TableName: !Ref CallRecords
      Events:
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref TowerApi
            Path: /beginAssistance
            Method: POST
  BasicAuthLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/
      Handler: handlers.auth
Outputs:
  ApiURL:
    Description: "API endpoint URL for Prod environment"
    Value: !Sub "https://${TowerApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/"
